"""Add V1.0 financial modeling

Revision ID: bd4817e7beb8
Revises: e666ed754130
Create Date: 2026-04-08 18:33:16.681794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd4817e7beb8'
down_revision: Union[str, Sequence[str], None] = 'e666ed754130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_cost_summaries',
    sa.Column('summary_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('machine_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('labour_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('material_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('last_calculated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('summary_id')
    )
    op.create_index(op.f('ix_job_cost_summaries_summary_id'), 'job_cost_summaries', ['summary_id'], unique=False)
    op.add_column('job_operations', sa.Column('quantity_completed', sa.Integer(), nullable=True))
    op.add_column('job_operations', sa.Column('quantity_rejected', sa.Integer(), nullable=True))
    op.alter_column('job_operations', 'actual_start_time',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=True,
               postgresql_using="actual_start_time::timestamp")
    op.alter_column('job_operations', 'actual_end_time',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=True,
               postgresql_using="actual_end_time::timestamp")
    op.add_column('machines', sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('parts', sa.Column('default_material_cost_per_unit', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('workers', sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'hourly_rate')
    op.drop_column('parts', 'default_material_cost_per_unit')
    op.drop_column('machines', 'hourly_rate')
    op.alter_column('job_operations', 'actual_end_time',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('job_operations', 'actual_start_time',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('job_operations', 'quantity_rejected')
    op.drop_column('job_operations', 'quantity_completed')
    op.drop_index(op.f('ix_job_cost_summaries_summary_id'), table_name='job_cost_summaries')
    op.drop_table('job_cost_summaries')
    # ### end Alembic commands ###
