"""Add quoted_price to Job

Revision ID: 6dee1d9c7adb
Revises: bd4817e7beb8
Create Date: 2026-04-08 20:17:06.697375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dee1d9c7adb'
down_revision: Union[str, Sequence[str], None] = 'bd4817e7beb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('quoted_price', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'quoted_price')
    # ### end Alembic commands ###
